language: php

php:
   - 5.3

env:
  global:
    - secure: "DQMsDlqVaQQEDln4Lt64hk6moMUTXIwIVNCyNSv7a9OOlKhZM3vV2Hr0vPsZ\n1mql04XVRSJ1LHkc/mrl6OFYxzxSQ07AGIz6eLUoM+wxIQE7ct9L1gae8uaO\n85bEBJa+JXD66xSolS4X7fMHni2K1Fa7J4ZEmNzAJmaNAVtcbHg="

before_script:
   - wget http://getcomposer.org/composer.phar
   - sh -c "if $TRAVIS_SECURE_ENV_VARS; then php composer.phar config github-oauth.github.com $GITHUB_OAUTH_TOKEN; else php composer.phar config preferred-install source; fi"

script:
   - php -dmemory_limit=1G composer.phar update --no-interaction
